apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  volumes:
    - name: nginx-content
      emptyDir: {}
  containers:
    - name: container-1
      image: nginx:alpine
      volumeMounts:
        - name: nginx-content
          mountPath: /usr/share/nginx/html
    - name: container-2
      image: busybox
      command:
        - "/bin/sh"
        - "-c"
        - 'while true; do echo "Hello from Container 2 (@ $(date))" >> /usr/share/nginx/html/index.html; sleep 5; done'
      volumeMounts:
        - name: nginx-content
          mountPath: /usr/share/nginx/html
